### ISSUE TITLE
Only set viewBox not height and width

### ISSUE THREAD

**Issue by hadley** [mdecorde/RSvgDevice#12]
We don't really care about the size of the final svg (and in fact we want it to be as flexible as possible so it can be embedded in a wide range of webpages), what we care about is the coordinate system.

(I'm pretty sure this is correct based on my reading of various viewport/viewbox tutorials on the web)

**Comment by timelyportfolio** [comment]
I would agree with this.  Thanks so much.   Most don't use `viewBox`, so this makes me happy.

**Comment by nathanwebb** [comment]
I've just come across a use case where height and width and very useful; wkhtmltopdf is unable to generate images if they don't have these fields.

After creating an html page with images generated using the standard svg device, I've been converting them to wkhtmltopdf. After switching to svglite, the images don't show up, unless I manually enter the height in the containing img tag. I think that's probably a bug in wkhtmltopdf, but it would be useful to add this as an option in svglite.
