### ISSUE TITLE
crashes RStudio

### ISSUE THREAD

**Issue by timelyportfolio** [mdecorde/RSvgDevice#19]
Each time I do `devSVG() ... dev.off()` my Windows 7 RStudio crashes.  However, the file is produced and saved.    I will update to 3.2.2 to  see if that changes the result.

![image](https://cloud.githubusercontent.com/assets/837910/9610155/60a68120-509d-11e5-81e6-1a5d3214e124.png)

```
Session info---------------------------------------------------------------
 setting  value                       
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, mingw32             
 ui       RStudio (0.99.473)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Chicago             

Packages-------------------------------------------------------------------
 package    * version    date       source                             
 devtools     1.6.1      2014-10-07 CRAN (R 3.1.2)                     
 rstudioapi   0.3.1      2015-06-05 Github (rstudio/rstudioapi@d0417a9)
 RSvgDevice * 0.6.4.9000 2015-09-01 local 
```

**Comment by hadley** [comment]
A reproducible example would be most helpful

**Comment by timelyportfolio** [comment]
This happens regardless of the contents between `devSVG()` and `dev.off`.  However, as I mentioned, a file is saved even though RStudio crashes.

```
devSVG()
plot(1:3)
dev.off()
```

or

```
devSVG()
contour(volcano)
dev.off()
```

**Comment by hadley** [comment]
Those both work fine for me. Are you sure you have the latest dev version?

**Comment by timelyportfolio** [comment]
Yes, in sync.  Wondering if something wrong with my build tools.  Only crashing in `x64`.

**Comment by hadley** [comment]
Does it output the closing `</svg>`?

If so, could you please help me debug by changing `SVG_Close` to:

```R
static void SVG_Close(pDevDesc dd) {
  SVGDesc *ptd = (SVGDesc *) dd->deviceSpecific;

  Rprintf("1");
  fprintf(ptd->texfp, "</svg>\n");

  Rprintf("2");
  fclose(ptd->texfp);

  Rprintf("3");
  free(ptd);
  Rprintf("4");
}
```

and telling me where it fails?

**Comment by hadley** [comment]
Try the dev version now. Should be fixed

**Comment by timelyportfolio** [comment]
It works :)
