### ISSUE TITLE
all points not rendered if pch = text

### ISSUE THREAD

**Issue by timelyportfolio** [mdecorde/RSvgDevice#23]
I ran into this as I was fooling around.  When `pch` is text, the last point is not rendered.  However if `pch` is numeric, it works as expected.

```
htmlSVG( plot(1:3,pch='R') )
xml_find_all( xmlSVG( plot(1:3,pch='R' ) ), ".//text[text()='R']" )
```

```
{xml_nodeset (2)}
[1] <text transform="translate(56.26,289.56)" font-size="10" fill="#00000 ...
[2] <text transform="translate(188.49,174.00)" font-size="10" fill="#0000 ...
```

![image](https://cloud.githubusercontent.com/assets/837910/9621188/0d7a6e98-50e9-11e5-9aab-524081fe4540.png)

**Comment by hadley** [comment]
Slightly more minimal reprex (with new `mini_plot()` helper):

```R
x <- xmlSVG(mini_plot(1:3, pch = c("a","b","c")))
xml_text(xml_find_all(x, ".//text"))
```

But not sure why this is happening - `SVG_Text()` just isn't getting called

**Comment by hadley** [comment]
It's getting cropped because the plot size is too small. Defaults have been made bigger, so this shouldn't be a problem any more

**Comment by timelyportfolio** [comment]
I discovered a similar clipping issue as I experimented with the examples in `dendextend`, but this time in the labels.

```r
library(RSvgDevice)


dend1 <- as.dendrogram(
   hclust(dist(c(1:5)),method="average")
)
dend1 <- rotate(dend1, order = c(as.character(5:1)))
labels(dend1) <- rev(
   c("dendextend", "let's u easily", "control",
     "(and compare) your", "dendrograms")
)
htmlSVG(plot(dend1))
```

**plot**
![image](https://cloud.githubusercontent.com/assets/837910/9704369/25ede840-546a-11e5-9d94-7284916e0478.png)


**SVG**
![image](https://cloud.githubusercontent.com/assets/837910/9704372/3216e112-546a-11e5-8028-233ad0467c07.png)
