### ISSUE TITLE
override print for lattice/ggplot2 for visual testing

### ISSUE THREAD

**Issue by timelyportfolio** [mdecorde/RSvgDevice#27]
Probably inadvisable, but I found this useful to leverage existing `lattice`/`ggplot2` examples as tests quickly and easily by overriding the `print` methods.

```r
print.ggplot <- function(x){
  htmlSVG(
    ggplot2:::print.ggplot(x)
  )
}

print.trellis <- function(x){
  htmlSVG(
    lattice:::print.trellis(x)
  )
}
```

For instance, I added in `common.R` from your `ggplot-book` with `results='asis'` and tested all the sections within a couple minutes.  Or, I `demo("lattice")` to do the whole set.

**Comment by timelyportfolio** [comment]
did the same for `xts::replot_xts()` which produces some complicated charts.  very pleasantly surprised by the results.

**Comment by hadley** [comment]
I think this is fine to do locally, but can't go in a package.

**Comment by timelyportfolio** [comment]
Just in case anyone is reading this.  A better idea from @hadley tweet suggests much easier to use `knitr` chunk option `dev` https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf
