### ISSUE TITLE
now plugs in nicely with svgPanZoom

### ISSUE THREAD

**Issue by timelyportfolio** [mdecorde/RSvgDevice#32]
The updated [`svgPanZoom`](http://cran.r-project.org/web/packages/svgPanZoom) accepts `xml2` so now works quite nicely with the helper `xmlSVG`.  Doubt that you want to add a dependency or need another helper function, but for closer/quicker inspection in RStudio Viewer this can be a good option.

![svgpanzoom_rsvgdevice](https://cloud.githubusercontent.com/assets/837910/9822763/d76ad166-5887-11e5-884c-da607afbc76d.gif)

**Comment by hadley** [comment]
Cool thanks - for the update
